import type { NextPage } from 'next';
import Head from 'next/head';
import { Grid, Row } from '../components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid>
        <Row center='xs'>
          <h1>Projects</h1>
        </Row>
      </Grid>

      <footer>
      </footer>
    </div>
  )
}

export default Home
